"""add sound change table

Revision ID: 8a18978a7dcb
Revises: b7bb80414c4b
Create Date: 2023-09-29 06:31:17.235875

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8a18978a7dcb"
down_revision = "b7bb80414c4b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sound_change_rules_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["language_id"], ["language_model.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sound_change_rules_model")
    # ### end Alembic commands ###
