"""add wordlink and word tables

Revision ID: 68aa230e9f89
Revises: d5b9ca44d768
Create Date: 2023-09-25 10:14:20.370119

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "68aa230e9f89"
down_revision = "d5b9ca44d768"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "word_link_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("definition", sa.String(), nullable=False),
        sa.Column("hint", sa.String(), nullable=True),
        sa.Column("part_of_speech", sa.String(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "word_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word", sa.String(), nullable=False),
        sa.Column("part_of_speech", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["language_id"], ["language_model.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "word_link_to_word",
        sa.Column("word_link_id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["word_model.id"],
        ),
        sa.ForeignKeyConstraint(
            ["word_link_id"],
            ["word_link_model.id"],
        ),
        sa.PrimaryKeyConstraint("word_link_id", "word_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("word_link_to_word")
    op.drop_table("word_model")
    op.drop_table("word_link_model")
    # ### end Alembic commands ###
