"""cascade delete words <-> word links

Revision ID: 0302dd5d9600
Revises: 68aa230e9f89
Create Date: 2023-09-26 09:46:58.242003

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "0302dd5d9600"
down_revision = "68aa230e9f89"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "word_link_to_word_word_link_id_fkey", "word_link_to_word", type_="foreignkey"
    )
    op.drop_constraint(
        "word_link_to_word_word_id_fkey", "word_link_to_word", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "word_link_to_word",
        "word_link_model",
        ["word_link_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "word_link_to_word", "word_model", ["word_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "word_link_to_word", type_="foreignkey")
    op.drop_constraint(None, "word_link_to_word", type_="foreignkey")
    op.create_foreign_key(
        "word_link_to_word_word_id_fkey",
        "word_link_to_word",
        "word_model",
        ["word_id"],
        ["id"],
    )
    op.create_foreign_key(
        "word_link_to_word_word_link_id_fkey",
        "word_link_to_word",
        "word_link_model",
        ["word_link_id"],
        ["id"],
    )
    # ### end Alembic commands ###
