"""add word classes

Revision ID: 527ee33afb14
Revises: 8a18978a7dcb
Create Date: 2023-09-30 21:10:19.445657

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "527ee33afb14"
down_revision = "8a18978a7dcb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "word_class_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("abbreviation", sa.String(), nullable=False),
        sa.Column("part_of_speech", sa.String(), nullable=False),
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["language_id"], ["language_model.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "word_class_to_word",
        sa.Column("word_class_id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["word_class_id"], ["word_class_model.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["word_id"], ["word_model.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("word_class_id", "word_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("word_class_to_word")
    op.drop_table("word_class_model")
    # ### end Alembic commands ###
