"""add language table

Revision ID: 3fb6729f6bcb
Revises: 3adfafe720ef
Create Date: 2023-09-24 11:18:05.925781

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3fb6729f6bcb"
down_revision = "3adfafe720ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "language_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user_model.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index("ix_user_model_email", table_name="user_model")
    op.create_index(
        op.f("ix_user_model_username"), "user_model", ["username"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_model_username"), table_name="user_model")
    op.create_index("ix_user_model_email", "user_model", ["username"], unique=False)
    op.drop_table("language_model")
    # ### end Alembic commands ###
