"""add phonology stuff

Revision ID: b7bb80414c4b
Revises: 0302dd5d9600
Create Date: 2023-09-27 13:13:11.614892

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b7bb80414c4b"
down_revision = "0302dd5d9600"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "phone_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("base_phone", sa.String(length=10), nullable=False),
        sa.Column("quality", sa.String(), nullable=True),
        sa.Column("graph", sa.String(), nullable=True),
        sa.Column("vowel", sa.Boolean(), nullable=False),
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["language_id"], ["language_model.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("phone_model")
    # ### end Alembic commands ###
