"""add audit timestamps

Revision ID: d5b9ca44d768
Revises: 3fb6729f6bcb
Create Date: 2023-09-24 11:21:16.054753

"""
import sqlalchemy as sa

from alembic import op
from app.utils.utils import get_now_int

# revision identifiers, used by Alembic.
revision = "d5b9ca44d768"
down_revision = "3fb6729f6bcb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "language_model",
        sa.Column(
            "created_at", sa.Integer(), nullable=False, server_default=f"{get_now_int}"
        ),
    )
    op.add_column(
        "language_model",
        sa.Column(
            "updated_at", sa.Integer(), nullable=False, server_default=f"{get_now_int}"
        ),
    )
    op.add_column(
        "user_model",
        sa.Column(
            "created_at", sa.Integer(), nullable=False, server_default=f"{get_now_int}"
        ),
    )
    op.add_column(
        "user_model",
        sa.Column(
            "updated_at", sa.Integer(), nullable=False, server_default=f"{get_now_int}"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_model", "updated_at")
    op.drop_column("user_model", "created_at")
    op.drop_column("language_model", "updated_at")
    op.drop_column("language_model", "created_at")
    # ### end Alembic commands ###
