"""add sound change to table cell

Revision ID: 7f01564d035a
Revises: e327ea6ca217
Create Date: 2023-10-03 07:30:41.608284

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7f01564d035a"
down_revision = "e327ea6ca217"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "grammar_table_cell_model",
        sa.Column("sound_change_rules_id", sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        None,
        "grammar_table_cell_model",
        "sound_change_rules_model",
        ["sound_change_rules_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "grammar_table_cell_model", type_="foreignkey")
    op.drop_column("grammar_table_cell_model", "sound_change_rules_id")
    # ### end Alembic commands ###
